import {
  Baby,
  Bone,
  Brain,
  HeartPulse,
  Stethoscope,
  Syringe,
  UserRound,
} from "lucide-react";

export const doctorCategories = [
  {
    id: "all",
    name: "All Doctors",
    count: 214,
    icon: Stethoscope,
    accent: "bg-emerald-50 text-emerald-700",
    specialty: null,
  },
  {
    id: "general",
    name: "General Physician",
    count: 128,
    icon: Stethoscope,
    accent: "bg-emerald-50 text-emerald-700",
    specialty: "General Physician",
  },
  {
    id: "pediatrician",
    name: "Pediatrician",
    count: 98,
    icon: Baby,
    accent: "bg-teal-50 text-teal-700",
    specialty: "Pediatrician",
  },
  {
    id: "cardiologist",
    name: "Cardiologist",
    count: 75,
    icon: HeartPulse,
    accent: "bg-rose-50 text-rose-600",
    specialty: "Cardiology",
  },
  {
    id: "dermatologist",
    name: "Dermatologist",
    count: 68,
    icon: Syringe,
    accent: "bg-amber-50 text-amber-600",
    specialty: "Dermatologist",
  },
  {
    id: "orthopedic",
    name: "Orthopedic",
    count: 62,
    icon: Bone,
    accent: "bg-lime-50 text-lime-700",
    specialty: "Orthopedic",
  },
  {
    id: "neurologist",
    name: "Neurologist",
    count: 45,
    icon: Brain,
    accent: "bg-slate-100 text-slate-700",
    specialty: "Neurologist",
  },
  {
    id: "gastro",
    name: "Gastroenterologist",
    count: 40,
    icon: UserRound,
    accent: "bg-emerald-50 text-emerald-700",
    specialty: "Gastroenterologist",
  },
];

export const doctors = [
  {
    id: "rahul-sharma",
    name: "Dr. Rahul Sharma",
    specialty: "Cardiologist",
    rating: 4.9,
    reviews: 124,
    experience: "12+ Years Exp.",
    location: "Mumbai, India",
    fee: 800,
    initials: "RS",
  },
  {
    id: "priya-patel",
    name: "Dr. Priya Patel",
    specialty: "Dermatologist",
    rating: 4.8,
    reviews: 98,
    experience: "8+ Years Exp.",
    location: "Delhi, India",
    fee: 700,
    initials: "PP",
  },
  {
    id: "amit-verma",
    name: "Dr. Amit Verma",
    specialty: "Orthopedic",
    rating: 4.7,
    reviews: 76,
    experience: "10+ Years Exp.",
    location: "Bangalore, India",
    fee: 750,
    initials: "AV",
  },
  {
    id: "neha-kapoor",
    name: "Dr. Neha Kapoor",
    specialty: "Neurologist",
    rating: 4.9,
    reviews: 112,
    experience: "9+ Years Exp.",
    location: "Pune, India",
    fee: 900,
    initials: "NK",
  },
  {
    id: "arjun-mehta",
    name: "Dr. Arjun Mehta",
    specialty: "General Physician",
    rating: 4.8,
    reviews: 142,
    experience: "11+ Years Exp.",
    location: "Ahmedabad, India",
    fee: 650,
    initials: "AM",
  },
  {
    id: "sana-khan",
    name: "Dr. Sana Khan",
    specialty: "Pediatrician",
    rating: 4.7,
    reviews: 88,
    experience: "7+ Years Exp.",
    location: "Jaipur, India",
    fee: 600,
    initials: "SK",
  },
];
